; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; =====================================================
; --- shared settings inherited by all environments ---
; =====================================================
[env:due]
platform = atmelsam
board = dueUSB
framework = arduino
; default_envs = due         ; by default builds `main` environment (if env not specified by `run` terminal cmd
monitor_speed = 115200      ; baud rate
lib_deps = 
    AxisEncoderShield3
    ArduinoMotorShieldR3


; build_src_filter = +<*> -<main.cpp> +<tof_wall_detection_test.cpp>
; build_src_filter = +<*> -<main.cpp> +<tof_wall_test_with_serialout.cpp>
; build_src_filter = +<*> -<main.cpp> +<test_button.cpp>
; build_src_filter = +<*> -<main.cpp> +<manual_flood_fill_no_drive.cpp>
build_src_filter = +<*> -<main.cpp> +<angle_control_test_with_profile.cpp>

#include "config.h"
#include "globals.h"
#include "tof.h"
#include "display.h"
#include "encoder.h"


monitor_filters = log2file, send_on_enter

; upload_port = /dev/cu.usbmodem101
; monitor_port = /dev/cu.usbmodem101


; [env:due]
; TO RUN MAIN:
; build_src_filter = -<src/tests/>
; TO RUN TESTS (other files with setup/loop structure FILES
; build_src_filter = -<fsm.cpp> -<controllers.cpp> -<motor_control.cpp> +<display.cpp> +<main.cpp> +<config.h>
; build_src_filter = -<main.cpp> +<tests/bno055_calibration.cpp>
; build_src_filter = -<main.cpp> +<tests/rotation_openloop_char.cpp>
