; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:due]
platform = atmelsam
board = dueUSB
framework = arduino
; monitor_speed = 9600
monitor_speed = 115200
lib_deps = 
	ArduinoMotorShieldR3
    AxisEncoderShield3
    ; AxisMotionShield9
; To include only a specific folder and ignore everything else in the src/ directory
; build_src_filter = -<*> +<folder_a/> +<common_utils.cpp>
; build_src_filter = -<*> +<ArduinoMotorShieldR3_demo.cpp>
; build_src_filter = -<*> +<AxisEncoderShield3_ex.cpp>
; build_src_filter = -<*> +<lab1_motor_char.cpp>
build_src_filter = -<*> +<lab2_motor_char.cpp>

upload_port = /dev/cu.usbmodem101
; monitor_port = /dev/cu.usbmodem1011
; monitor_filters = default, log2file

