; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; =====================================================
; --- shared settings inherited by all environments ---
; =====================================================
[env]                       ; [env:due]
platform = atmelsam
board = dueUSB
framework = arduino
default_envs = main         ; by default builds `main` environment (if env not specified by `run` terminal cmd
monitor_speed = 115200      ; baud rate
monitor_filters = log2file
lib_deps = 
    AxisEncoderShield3
    ArduinoMotorShieldR3
    VL53L4CD_ArduinoLib
    Adafruit BNO055
    Adafruit_BusIO
    Adafruit SSD1306
    Adafruit GFX Library

; =====================================================
; --- Main: src/main.cpp + all files in /src dir ---
; =====================================================
[env:main]
build_src_filter = -<*> +<main.cpp> +<display.cpp> +<display.h> +<config.h> +<globals.h>

; To include only a specific folder (or file) and ignore everything else in the src/ directory
; build_src_filter = -<*> +<folder_a/> +<common_utils.cpp>
; build_src_filter = -<*> +<filename.cpp>

; [env:display]
; build_src_filter = -<*> +<display.cpp>


; =====================================================
; --- Tests: environments for diff files in /test dir ---
; =====================================================
; test_build_src_filter controls which src/ files are compiled in addition to the test file
; (each only compiles the src/ files needed by that test file) 
; always exclude main.cpp !! (has its own setup/loop which create a conflict)

[env:test_encoder_cal]
test_build_src_filter = -<*> +<globals.cpp> +<sensors.cpp>

[env:test_tof]
test_build_src_filter = -<*> +<globals.cpp> +<sensors.cpp>

[env:test_imu]
test_build_src_filter = -<*> +<globals.cpp> +<sensors.cpp>

[env:test_drive_straight]
test_build_src_filter = -<*> +<globals.cpp> +<sensors.cpp> +<control.cpp>

[env:test_turn_90]
test_build_src_filter = -<*> +<globals.cpp> +<sensors.cpp> +<control.cpp>


; platform = atmelsam
; board = dueUSB
; framework = arduino
; monitor_speed = 115200      ; baud rate
; lib_deps = 
;     AxisEncoderShield3
;     ; Adafruit_BusIO
;     ArduinoMotorShieldR3
;     VL53L4CD_ArduinoLib
; To include only a specific folder and ignore everything else in the src/ directory
; build_src_filter = -<*> +<folder_a/> +<common_utils.cpp>
; build_src_filter = -<*> +<ArduinoMotorShieldR3_demo.cpp>
; build_src_filter = -<*> +<AxisEncoderShield3_ex.cpp>
; build_src_filter = -<*> +<lab1_motor_char.cpp>
; build_src_filter = -<*> +<motor_openloop_test.cpp>


; upload_port = /dev/cu.usbmodem101
; monitor_port = /dev/cu.usbmodem1011

; build_flags = -DPWM_COMMAND=${sysenv.TEST_PWM_VAL}
